print("Content-Type: text/html")
print("\r\n\r\n")
print("<html>")
print(" <head>")
print("  <title>Hello World</title>")
print(" </head>")
print(" <body>")
print(" <?php echo '<p>Hello World</p>'; ?>")
print(" </body>")
print("</html>")